apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-webdata
spec:
    resources:
        requests:
            storage: {{ .Values.odoo.webdata.storage }}
    volumeMode: Filesystem
    accessModes:
    - ReadWriteMany
    storageClassName: {{ .Values.odoo.webdata.className }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ .Release.Name }}-addons
spec:
    resources:
        requests:
            storage: {{ .Values.odoo.addons.storage }}
    volumeMode: Filesystem
    accessModes:
    - ReadWriteMany
    storageClassName: {{ .Values.odoo.addons.className }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ .Release.Name }}-pgdata
spec:
    resources:
        requests:
            storage: {{ .Values.postgres.data.storage }}
    accessModes:
    - ReadWriteOnce
    storageClassName: {{ .Values.postgres.data.className }}